[tool.poetry]
name = "secure-data-encryption"
version = "0.1.0"
readme = "README.md"
authors = ["syeda maham amjad"]
license = "MIT"
package-mode = false 

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
streamlit = "*"
cryptography = "*"
